### ISSUE TITLE
`Mexpect` for expecting prompt

### ISSUE THREAD

**Issue by talha252** [itublg/calico#1]
Students often ignore the given instructions when they are implementing the assigned algorithm. Sometimes, even though the result they produced is the correct, we failed to evaluate the program properly because they didn't follow the given prompt instructions precisely. Currently, _Calico_ evaluates this situation as **FAILED** but I think it should be evaluated as **ERROR**. To make it clear, an example would be:

```
...
     script:
        - expect: '[Ee]nter [Cc]ards?(.*?):\s+' # timeout: 2
        - send: 'c1'
        - send: 's1'
        - send: 'c1'
        - send: 's1'
        - send: '.'      
        - expect: '[Ee]nter [Mm]oves?(.*?):\s+' # timeout: 2
        - send: 'd'
        - send: 'd'
        - send: 'd'
        - send: 'd'
        - send: 'd'
        - send: '.'
        - expect: '[Ee]nter [Gg]oal(.*?):\s+' # timeout: 2
        - send: '42'
        - expect: '[Ss]core:\s+3' # timeout: 2
        - expect: _EOF_
...
```
Let's assume the student produce the correct result which is `Score: 3`. However, if the previous prompt was `Enter Goal` (without colon) the evaluation would stuck at that point and when the timeout expired, it would procude FAILED. Nevertheless, the result was correct but we didn't even reach that point. Let's change `expect` with `mexpect`.

```
...
     script:
        - mexpect: '[Ee]nter [Cc]ards?(.*?):\s+' # timeout: 2
        - send: 'c1'
        - send: 's1'
        - send: 'c1'
        - send: 's1'
        - send: '.'      
        - mexpect: '[Ee]nter [Mm]oves?(.*?):\s+' # timeout: 2
        - send: 'd'
        - send: 'd'
        - send: 'd'
        - send: 'd'
        - send: 'd'
        - send: '.'
        - mexpect: '[Ee]nter [Gg]oal(.*?):\s+' # timeout: 2
        - send: '42'
        - expect: '[Ss]core:\s+3' # timeout: 2
        - expect: _EOF_
...
```
In this case, if we stuck at `Enter Goal` part, now we expect **ERROR** from _Calico_  rather than **FAILED** . 

In a nutshell, my proposal is that we should use `expect` when we are expecting a **result** from the user and `mexpect` when we are expecting non-critical things like a **menu prompt**.
