### ISSUE TITLE
Generating test files automatically

### ISSUE THREAD

**Issue by Asocia** [itublg/calico#9]
I know it's not the main concern of _calico_ to fulfill such a task but most of the test files requires the tester to do similar things: 
1. Tester generally writes his/her program and then runs it, taking notes of inputs and outputs of the program on one hand. 

2. S/he then writes "expect", "send" actions for a test case by taking care of [metacharacters](https://docs.python.org/3/howto/regex.html#matching-characters) that appears in the output of the program and escapes them properly. 

3. S/he runs the program again with different input, if the previous test case's scheme is similar to new one, copy pastes it and modifies it for the new values otherwise jumps to 2. 

4. Repeats 2. and 3. continuously until s/he thinks the coverage of test cases are enough.

So it's repetitive, time consuming and attention-requiring process. But most of it can be automated. The only part that "a human is really required" is when deciding the inputs of the program. Writing the actions _expect_, _send_, setting _return_ values and escaping metacharacters, all can be automated.

So I think it would be nice to have something like this:

`$ ./eval_exp`
Give me a simple expression to evaluate: <ins>2 * 3</ins>
2 * 3 is 6.

`$ calico --generate-test-file test.t "./eval_exp"`
Enter the number of test cases do you want: <ins>1</ins>

Running for case_1...
Give me a simple expression to evaluate: <ins>3 + 5</ins>
3 + 5 is 8.
Assign points for this run: <ins>5</ins>

All test cases have been generated. Exiting.

`$ cat test.t`
\## Placeholder for building the executable if required.
case_1:
&nbsp;&nbsp;&nbsp;&nbsp;run: ./eval_exp
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;script:
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;- expect: "Give me a simple expression to evaluate: "
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;- send: "3 + 5"
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;- expect: "3 [+] 5 is 8[.][\r\n]"
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;- expect: \_EOF\_
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return: 0
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;points: 5

The prompts in the interactive part may be overwhelming but I included them to elucidate my idea. 

And that's all, thanks for taking time to read.

**Comment by Asocia** [comment]
This idea came to my mind last week. I worked a bit at the implementation and currently I'm able to produce this:
`$ python3 capture_io.py "./circle"`
<ins>\~</ins>
Enter radius of circle: <ins>3</ins>
Area: 28.274309
<ins>\~</ins>
./circle program ended.
('output', 'Enter radius of circle: ')
('input', '3\n')
('output', 'Area: 28.274309\n')
('return code', 0)

The tilde (~) signs are not part of "./circle" program. They have meanings in my implementation and unfortunately I couldn't find a way to get rid of them. I'll finish and send a PR when I have free time but I believe there are more elegant ways to do this. (asyncio, multiprocessing, threading are the libraries that I think could help but my knowledge on these are very limited. )

**Comment by talha252** [comment]
I am not sure why you need a multitasking library to solve this?

The first observation of yours is good. However, rather than generating verbose test file, I would prefer to make it concise. I think the problem you mention can be solved with a new property which I am going to call it _algorithm_ block. Here is a probable algorithm block:
```
_define:
    algorithms:
       simple_alg: 
            - expect: "Give me a simple expression to evaluate: "
            - send: <<param1>>
            - expect: <<param2>>
            - expect: _EOF_
case_1:
    run: ./eval_exp
        script:
            - algorithm: simple_alg
                - param1: "3 + 5"
                - param2: "3 [+] 5 is 8[.][\r\n]"
        return: 0
        points: 5

case_2:
    run: ./eval_exp
        script:
            - algorithm: simple_alg
                - param1: "8 + 9"
                - param2: "8 [+] 9 is 17[.][\r\n]"
        return: 0
        points: 5
```
I haven't thought on the exact syntax of this attribute but I think that this would allow for the tester to write much more concise test files. Also, it is possible to chain multiple algorithm block which would have made the test file much smaller. The only drawback is that this is much harder to parse, it requires a lot of error checking and if it is not done correctly it's prone to unexpected errors.
